### ISSUE TITLE
Lasalle College/ArtInstitute of Vancouver

### ISSUE THREAD

**Issue by SaintJeanDesign** [sergei1152/WhatsMyGPA#17]
The Art Institute of Vancouver was active during the year of 2013-2014 it has most recently been replaced by Lasalle College.

Neither of these institutions are included in your GPA calculator

**Comment by sergei1152** [comment]
@SaintJeanDesign  can you tell me the grading system Lasalle uses and possibly a link to a conversion chart? Also if possible the credit weights that the school uses for its courses. I can't find anything online myself.

**Comment by sergei1152** [comment]
@SaintJeanDesign  If you wanna phone them for me and let me know the conversion chart I'll be happy to add it to the calculator. I do prefer having an HTML or website source I can link however.

**Comment by SaintJeanDesign** [comment]
Provincial credability can be looked up on a government website,

I found another resource that didn’t require the institution name.
