### ISSUE TITLE
Mohawk college is missing

### ISSUE THREAD

**Issue by sihaam** [sergei1152/WhatsMyGPA#3]
Hi, I'm trying to calculate my gpa. Cant find it anywhere on the list. Not sure how to add it. Can someone please help

**Comment by sergei1152** [comment]
Thanks, for letting me know. I'll try to get it added as soon as I can.

**Comment by sergei1152** [comment]
The calculator has been updated to include Mohawlk College. Note that it looks like the grading system for the college is only exclusively percentages, so keep in mind that the gpa conversion is an approximation.
