### ISSUE TITLE
Missing school

### ISSUE THREAD

**Issue by I-amHeidi** [sergei1152/WhatsMyGPA#6]
Hi there, 
Niagara College is missing

**Comment by the-clockwork-feline** [comment]
Sheridan college is missing and they use a percent grading system

**Comment by SELoftus** [comment]
New Brunswick Community College is missing. They use a percent grading system, and their GPA calculation page is here: http://nbcc.ca/docs/default-source/policies/gpa-calculation.pdf?sfvrsn=2

**Comment by TheBigR96** [comment]
Still missing Niagara College, Welland, ON

**Comment by sergei1152** [comment]
Hey @I-amHeidi  sorry for the late reply. Could you let me know what grading system Niagara uses? I couldn't find anything on their website. If you have a conversion chart that may be on the website that would also be ideal, as well as what credit weights are common for the courses there.

**Comment by sergei1152** [comment]
@the-clockwork-feline @SELoftus I added your suggested colleges.
